//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderForm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:TextBox1]")]
        public string barcodetb {
            get {
                return ((string)(this["barcodetb"]));
            }
            set {
                this["barcodetb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Label56]")]
        public string invoiceprc {
            get {
                return ((string)(this["invoiceprc"]));
            }
            set {
                this["invoiceprc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:TextBox8]")]
        public string invoicenotes {
            get {
                return ((string)(this["invoicenotes"]));
            }
            set {
                this["invoicenotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME: ButtonX1]")]
        public string btntogo {
            get {
                return ((string)(this["btntogo"]));
            }
            set {
                this["btntogo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME: ButtonX11]")]
        public string btnphone {
            get {
                return ((string)(this["btnphone"]));
            }
            set {
                this["btnphone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Button1]")]
        public string btn1 {
            get {
                return ((string)(this["btn1"]));
            }
            set {
                this["btn1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Button2]")]
        public string btn2 {
            get {
                return ((string)(this["btn2"]));
            }
            set {
                this["btn2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Button3]")]
        public string btn3 {
            get {
                return ((string)(this["btn3"]));
            }
            set {
                this["btn3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Button4]")]
        public string btn4 {
            get {
                return ((string)(this["btn4"]));
            }
            set {
                this["btn4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Button5]")]
        public string btn5 {
            get {
                return ((string)(this["btn5"]));
            }
            set {
                this["btn5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Button6]")]
        public string btn6 {
            get {
                return ((string)(this["btn6"]));
            }
            set {
                this["btn6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Button7]")]
        public string btn7 {
            get {
                return ((string)(this["btn7"]));
            }
            set {
                this["btn7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Button8]")]
        public string btn8 {
            get {
                return ((string)(this["btn8"]));
            }
            set {
                this["btn8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Button9]")]
        public string btn9 {
            get {
                return ((string)(this["btn9"]));
            }
            set {
                this["btn9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Button12]")]
        public string btn0 {
            get {
                return ((string)(this["btn0"]));
            }
            set {
                this["btn0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Button13]")]
        public string btnsubmit {
            get {
                return ((string)(this["btnsubmit"]));
            }
            set {
                this["btnsubmit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Label25]")]
        public string amountlbl {
            get {
                return ((string)(this["amountlbl"]));
            }
            set {
                this["amountlbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:TextBox5]")]
        public string CashTextBox {
            get {
                return ((string)(this["CashTextBox"]));
            }
            set {
                this["CashTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Label34]")]
        public string SaveBTN {
            get {
                return ((string)(this["SaveBTN"]));
            }
            set {
                this["SaveBTN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:SwitchButton1]")]
        public string SwitchBTN {
            get {
                return ((string)(this["SwitchBTN"]));
            }
            set {
                this["SwitchBTN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" نقطة بيع مطعم سحائب طيبه سليمانية 2022")]
        public string pos {
            get {
                return ((string)(this["pos"]));
            }
            set {
                this["pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:TextBox22]")]
        public string Mada1 {
            get {
                return ((string)(this["Mada1"]));
            }
            set {
                this["Mada1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:TextBox25]")]
        public string Mada2 {
            get {
                return ((string)(this["Mada2"]));
            }
            set {
                this["Mada2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:TextBox27]")]
        public string Mada3 {
            get {
                return ((string)(this["Mada3"]));
            }
            set {
                this["Mada3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:TextBox29]")]
        public string PartCash {
            get {
                return ((string)(this["PartCash"]));
            }
            set {
                this["PartCash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:ComboBox15]")]
        public string Mada1Combo {
            get {
                return ((string)(this["Mada1Combo"]));
            }
            set {
                this["Mada1Combo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:ComboBox16]")]
        public string Mada2Combo {
            get {
                return ((string)(this["Mada2Combo"]));
            }
            set {
                this["Mada2Combo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:ComboBox17]")]
        public string Mada3Combo {
            get {
                return ((string)(this["Mada3Combo"]));
            }
            set {
                this["Mada3Combo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Filename=C:\\db\\db.db")]
        public string DBConnection {
            get {
                return ((string)(this["DBConnection"]));
            }
            set {
                this["DBConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int defaultOrder {
            get {
                return ((int)(this["defaultOrder"]));
            }
            set {
                this["defaultOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:TextBox4]")]
        public string InvoiceNumberTB {
            get {
                return ((string)(this["InvoiceNumberTB"]));
            }
            set {
                this["InvoiceNumberTB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Label30]")]
        public string InvoiceTime {
            get {
                return ((string)(this["InvoiceTime"]));
            }
            set {
                this["InvoiceTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Libra Soft® مطعم سحائب طيبه سليمانية 2023")]
        public string POSMainName {
            get {
                return ((string)(this["POSMainName"]));
            }
            set {
                this["POSMainName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Label35]")]
        public string POSNewBTN {
            get {
                return ((string)(this["POSNewBTN"]));
            }
            set {
                this["POSNewBTN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:ToolStrip3]")]
        public string POSShortcut {
            get {
                return ((string)(this["POSShortcut"]));
            }
            set {
                this["POSShortcut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:Label222]")]
        public string POSWinShortcut {
            get {
                return ((string)(this["POSWinShortcut"]));
            }
            set {
                this["POSWinShortcut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME: Button10]")]
        public string POSClearNumber {
            get {
                return ((string)(this["POSClearNumber"]));
            }
            set {
                this["POSClearNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public decimal CurrentTax {
            get {
                return ((decimal)(this["CurrentTax"]));
            }
            set {
                this["CurrentTax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("فرع السليمانية")]
        public string BranchName {
            get {
                return ((string)(this["BranchName"]));
            }
            set {
                this["BranchName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestingMode {
            get {
                return ((bool)(this["TestingMode"]));
            }
            set {
                this["TestingMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("oven2")]
        public string DefaultPrinter {
            get {
                return ((string)(this["DefaultPrinter"]));
            }
            set {
                this["DefaultPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showMenu {
            get {
                return ((bool)(this["showMenu"]));
            }
            set {
                this["showMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseWindow {
            get {
                return ((bool)(this["CloseWindow"]));
            }
            set {
                this["CloseWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int Fnt {
            get {
                return ((int)(this["Fnt"]));
            }
            set {
                this["Fnt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial")]
        public string FontCombo {
            get {
                return ((string)(this["FontCombo"]));
            }
            set {
                this["FontCombo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:TextBox6]")]
        public string POSPhoneNumber {
            get {
                return ((string)(this["POSPhoneNumber"]));
            }
            set {
                this["POSPhoneNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NAME:TextBox7]")]
        public string POSClientName {
            get {
                return ((string)(this["POSClientName"]));
            }
            set {
                this["POSClientName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WheelEnabled {
            get {
                return ((bool)(this["WheelEnabled"]));
            }
            set {
                this["WheelEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WheelGridEnabled {
            get {
                return ((bool)(this["WheelGridEnabled"]));
            }
            set {
                this["WheelGridEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http:\\\\192.168.1.7:5000")]
        public string API_Connection {
            get {
                return ((string)(this["API_Connection"]));
            }
            set {
                this["API_Connection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200,222")]
        public global::System.Windows.Size ItemSize {
            get {
                return ((global::System.Windows.Size)(this["ItemSize"]));
            }
            set {
                this["ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("سحائب طييبة")]
        public string RestaurantName {
            get {
                return ((string)(this["RestaurantName"]));
            }
            set {
                this["RestaurantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\db\\images\\debes.png")]
        public string Logo {
            get {
                return ((string)(this["Logo"]));
            }
            set {
                this["Logo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POS")]
        public string CashierPrinter {
            get {
                return ((string)(this["CashierPrinter"]));
            }
            set {
                this["CashierPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Api_Server {
            get {
                return ((bool)(this["Api_Server"]));
            }
            set {
                this["Api_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Api_On {
            get {
                return ((bool)(this["Api_On"]));
            }
            set {
                this["Api_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CallerIDEnabled {
            get {
                return ((bool)(this["CallerIDEnabled"]));
            }
            set {
                this["CallerIDEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string API_Server_Path {
            get {
                return ((string)(this["API_Server_Path"]));
            }
            set {
                this["API_Server_Path"] = value;
            }
        }
    }
}
